#┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#┃ 📁File      📄 locale.jl                                                         ┃
#┃ 📙Brief     📝 Locale Configuration Module for Blunux Self-Build                 ┃
#┃ 🧾Details   🔎 Handles locale, timezone, keyboard, and input method setup        ┃
#┃ 🚩OAuthor   🦋 Blunux Project                                                    ┃
#┃ 👨‍🔧LAuthor   👤 Blunux Project                                                    ┃
#┃ 📆LastDate  📍 2026-01-25 🔄Please support to keep update🔄                      ┃
#┃ 🏭License   📜 MIT License                                                       ┃
#┃ ✅Guarantee ⚠️ Explicitly UN-guaranteed                                          ┃
#┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
#=
Locale configuration module for Blunux Self-Build Tool

Handles locale, timezone, and keyboard configuration.
=#

"""
Common locale to encoding mapping.
"""
const LOCALE_ENCODINGS = Dict(
    "ko_KR" => "UTF-8",
    "en_US" => "UTF-8",
    "ja_JP" => "UTF-8",
    "zh_CN" => "UTF-8",
    "zh_TW" => "UTF-8",
    "de_DE" => "UTF-8",
    "fr_FR" => "UTF-8",
    "es_ES" => "UTF-8",
    "pt_BR" => "UTF-8",
    "ru_RU" => "UTF-8",
    "it_IT" => "UTF-8",
    "pl_PL" => "UTF-8",
    "sv_SE" => "UTF-8",
    "nb_NO" => "UTF-8",
    "da_DK" => "UTF-8",
    "fi_FI" => "UTF-8",
    "nl_NL" => "UTF-8",
)

"""
    configure_locale(profile_dir, locale_config)

Configure locale settings in the archiso profile.
"""
function configure_locale(profile_dir, locale_config)
    airootfs_dir = joinpath(profile_dir, "airootfs")
    scripts_dir = joinpath(airootfs_dir, "root", "blunux-setup")
    mkpath(scripts_dir)

    # Get locale settings
    language = get(locale_config, "language", "en_US")
    timezone = get(locale_config, "timezone", "UTC")
    keyboards = get(locale_config, "keyboard", ["us"])

    # Ensure language is an array
    if language isa String
        language = [language]
    end

    # Ensure keyboards is an array
    if keyboards isa String
        keyboards = [keyboards]
    end

    println("    Language: $(join(language, ", "))")
    println("    Timezone: $timezone")
    println("    Keyboards: $(join(keyboards, ", "))")

    # Create locale setup script
    setup_script = joinpath(scripts_dir, "setup-locale.sh")

    # Process all languages - use first as default
    locales_to_enable = String[]
    for lang in language
        locale_base = split(lang, ".")[1]
        encoding = get(LOCALE_ENCODINGS, locale_base, "UTF-8")
        push!(locales_to_enable, "$locale_base.$encoding")
    end

    # Always include en_US.UTF-8 as fallback
    if !("en_US.UTF-8" in locales_to_enable)
        push!(locales_to_enable, "en_US.UTF-8")
    end

    # Default locale is the first one
    full_locale = locales_to_enable[1]

    # Generate sed commands for all locales
    sed_commands = join(["sed -i 's/^#\\\\($loc\\\\)/\\\\1/' /etc/locale.gen" for loc in locales_to_enable], "\n")

    open(setup_script, "w") do f
        print(f, """
#!/bin/bash
# Blunux Locale Setup Script
# Generated by blunux_selfbuild

set -e

echo "Setting up locale and timezone..."

# Configure locale
echo "Configuring locales: $(join(locales_to_enable, ", "))"

# Uncomment the required locales in locale.gen
$sed_commands

# Generate locales
locale-gen

# Set system locale
echo "LANG=$full_locale" > /etc/locale.conf
export LANG=$full_locale

# Configure timezone
echo "Setting timezone: $timezone"
ln -sf /usr/share/zoneinfo/$timezone /etc/localtime
hwclock --systohc

# Configure keyboard layouts
echo "Setting keyboard layouts: $(join(keyboards, ", "))"
""")

        # X11 keyboard configuration
        print(f, """

# Create X11 keyboard configuration
mkdir -p /etc/X11/xorg.conf.d
cat > /etc/X11/xorg.conf.d/00-keyboard.conf << 'XKBEOF'
Section "InputClass"
    Identifier "system-keyboard"
    MatchIsKeyboard "on"
    Option "XkbLayout" "$(join(keyboards, ","))"
XKBEOF
""")

        # If multiple layouts, add options for switching
        if length(keyboards) > 1
            print(f, """
    Option "XkbOptions" "grp:alt_shift_toggle"
""")
        end

        print(f, """
echo 'EndSection' >> /etc/X11/xorg.conf.d/00-keyboard.conf
""")

        # Console keyboard configuration
        print(f, """

# Set console keyboard layout
echo "KEYMAP=$(keyboards[1])" > /etc/vconsole.conf

echo "Locale and timezone configuration complete."
""")
    end

    chmod(setup_script, 0o755)
    println("    Created locale setup script")

    # Also configure in the profile for live environment
    configure_profile_locale(profile_dir, full_locale, timezone, keyboards)
end

"""
    configure_profile_locale(profile_dir, locale, timezone, keyboards)

Configure locale directly in the archiso profile files.
"""
function configure_profile_locale(profile_dir, locale, timezone, keyboards)
    airootfs_dir = joinpath(profile_dir, "airootfs")

    # Create /etc directory structure
    etc_dir = joinpath(airootfs_dir, "etc")
    mkpath(etc_dir)

    # Write locale.gen with required locales
    locale_gen = joinpath(etc_dir, "locale.gen")
    open(locale_gen, "w") do f
        # Always include en_US.UTF-8 and C.UTF-8
        println(f, "en_US.UTF-8 UTF-8")
        println(f, "C.UTF-8 UTF-8")
        # Add the requested locale if different
        if !startswith(locale, "en_US") && !startswith(locale, "C.")
            println(f, "$locale UTF-8")
        end
    end

    # Write locale.conf - use C.UTF-8 for live environment stability
    # User's locale will be configured during installation
    locale_conf = joinpath(etc_dir, "locale.conf")
    open(locale_conf, "w") do f
        println(f, "LANG=C.UTF-8")
    end

    # Write vconsole.conf
    vconsole_conf = joinpath(etc_dir, "vconsole.conf")
    open(vconsole_conf, "w") do f
        println(f, "KEYMAP=$(keyboards[1])")
        println(f, "FONT=ter-v16n")
    end

    # Create X11 keyboard configuration
    xorg_conf_dir = joinpath(etc_dir, "X11", "xorg.conf.d")
    mkpath(xorg_conf_dir)

    keyboard_conf = joinpath(xorg_conf_dir, "00-keyboard.conf")
    open(keyboard_conf, "w") do f
        print(f, """
Section "InputClass"
    Identifier "system-keyboard"
    MatchIsKeyboard "on"
    Option "XkbLayout" "$(join(keyboards, ","))"
""")
        if length(keyboards) > 1
            println(f, "    Option \"XkbOptions\" \"grp:alt_shift_toggle\"")
        end
        println(f, "EndSection")
    end

    println("    Configured profile locale files")
end

"""
    configure_input_method(profile_dir, input_config, packages)

Configure input method settings.
"""
function configure_input_method(profile_dir, input_config, packages)
    if !get(input_config, "enabled", false)
        println("    Input method disabled")
        return
    end

    engine = get(input_config, "engine", "")
    if isempty(engine)
        println("    No input method engine specified")
        return
    end

    println("    Configuring input method: $engine")

    airootfs_dir = joinpath(profile_dir, "airootfs")
    scripts_dir = joinpath(airootfs_dir, "root", "blunux-setup")
    mkpath(scripts_dir)

    # Create input method setup script
    setup_script = joinpath(scripts_dir, "setup-input-method.sh")

    open(setup_script, "w") do f
        print(f, """
#!/bin/bash
# Blunux Input Method Setup Script
# Engine: $engine

set -e

echo "Setting up input method: $engine"

""")

        if startswith(engine, "fcitx5")
            # Fcitx5 configuration
            print(f, """
# Configure Fcitx5 environment variables
cat >> /etc/environment << 'EOF'
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
GLFW_IM_MODULE=ibus
EOF

# Create autostart for Fcitx5
mkdir -p /etc/xdg/autostart
cat > /etc/xdg/autostart/fcitx5.desktop << 'EOF'
[Desktop Entry]
Name=Fcitx 5
GenericName=Input Method
Comment=Start Input Method
Exec=fcitx5
Icon=fcitx
Terminal=false
Type=Application
Categories=System;Utility;
X-GNOME-Autostart-Phase=Applications
X-GNOME-AutoRestart=false
X-GNOME-Autostart-Notify=false
X-KDE-autostart-after=panel
EOF

echo "Fcitx5 configured successfully."
""")
        elseif startswith(engine, "ibus")
            # IBus configuration
            print(f, """
# Configure IBus environment variables
cat >> /etc/environment << 'EOF'
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
EOF

# Create autostart for IBus
mkdir -p /etc/xdg/autostart
cat > /etc/xdg/autostart/ibus.desktop << 'EOF'
[Desktop Entry]
Name=IBus Daemon
GenericName=Input Method Framework
Comment=Start IBus Daemon
Exec=ibus-daemon -drxR
Icon=ibus
Terminal=false
Type=Application
Categories=System;Utility;
X-GNOME-Autostart-Phase=Applications
EOF

echo "IBus configured successfully."
""")
        elseif engine == "kime"
            # Kime configuration (Korean)
            print(f, """
# Configure Kime environment variables
cat >> /etc/environment << 'EOF'
GTK_IM_MODULE=kime
QT_IM_MODULE=kime
XMODIFIERS=@im=kime
EOF

# Create Kime configuration directory
mkdir -p /etc/xdg/kime

# Create autostart for Kime
mkdir -p /etc/xdg/autostart
cat > /etc/xdg/autostart/kime.desktop << 'EOF'
[Desktop Entry]
Name=Kime
GenericName=Korean Input Method
Comment=Kime Input Method Daemon
Exec=kime
Icon=kime
Terminal=false
Type=Application
Categories=System;Utility;
X-GNOME-Autostart-Phase=Applications
EOF

echo "Kime configured successfully."
""")
        end

        print(f, """

echo "Input method setup complete."
""")
    end

    chmod(setup_script, 0o755)
    println("    Created input method setup script")
end
